function [fitresult, gof, output] = createLorentzianFit(wn, y)
%CREATEFIT(WN,Y)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : wn
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 03-May-2016 09:28:29


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( wn, y );

% Set up fittype and options.
ft = fittype( 'a*exp(-(x-c)^2/b^2)+d', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 100 -Inf];
[~, idx] = max(y);
opts.StartPoint = [max(y)-min(y) 200 wn(idx) min(y)];
opts.Upper = [Inf Inf 10000 Inf];

% Fit model to data.
[fitresult, gof, output] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData);
legend( h, 'y vs. wn', 'Excluded y vs. wn', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel wn
ylabel y
grid on


